package ViewModel;

import Fragment.Assets;

import javax.swing.*;
import java.awt.*;

public class AssetsForm {

    private JCheckBox enableSaleValueCheckBox;
    private JCheckBox enableRentabilityCheckBox;
    private JTextField assetNameField;
    private JComboBox assetTypeCemboBox;
    private JTextField rentabilityPercentageField;
    private JComboBox assetCategoryComboBox;
    private JTextField saleValueField;
    private JPanel assetsPanel;

    public String getAssetName() {
        return assetNameField.getText();
    }

    public byte getAssetType() {
        if (assetTypeCemboBox.getSelectedIndex() == 1) {
            return Assets.CURRENT;
        } else if (assetTypeCemboBox.getSelectedIndex() == 2) {
            return Assets.NO_CURRENT;

        } else {
            return Assets.NONE;
        }

    }

    public int getRentabilityPercentage() {
        return Integer.valueOf(rentabilityPercentageField.getText());
    }

    public String getAssetCategory() {
        return assetCategoryComboBox.getSelectedItem().toString();
    }

    public Integer getSaleValue() {
        return Integer.valueOf(saleValueField.getText());
    }

    public AssetsForm() {
        {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
            $$$setupUI$$$();
        }
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        assetsPanel = new JPanel();
        assetsPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Nombre");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        assetsPanel.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        assetsPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        assetsPanel.add(spacer2, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Tipo");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        assetsPanel.add(label2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        assetsPanel.add(spacer3, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("% rentabilidad");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        assetsPanel.add(label3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        assetsPanel.add(spacer4, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Categoría");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        assetsPanel.add(label4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        assetsPanel.add(spacer5, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Valor aprox de venta");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        assetsPanel.add(label5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.VERTICAL;
        assetsPanel.add(spacer6, gbc);
        assetNameField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        assetsPanel.add(assetNameField, gbc);
        assetTypeCemboBox = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        assetsPanel.add(assetTypeCemboBox, gbc);
        rentabilityPercentageField = new JTextField();
        rentabilityPercentageField.setEnabled(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        assetsPanel.add(rentabilityPercentageField, gbc);
        assetCategoryComboBox = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        assetsPanel.add(assetCategoryComboBox, gbc);
        saleValueField = new JTextField();
        saleValueField.setEnabled(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        assetsPanel.add(saleValueField, gbc);
        enableSaleValueCheckBox = new JCheckBox();
        enableSaleValueCheckBox.setSelected(false);
        enableSaleValueCheckBox.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        assetsPanel.add(enableSaleValueCheckBox, gbc);
        enableRentabilityCheckBox = new JCheckBox();
        enableRentabilityCheckBox.setSelected(false);
        enableRentabilityCheckBox.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        assetsPanel.add(enableRentabilityCheckBox, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return assetsPanel;
    }

}
