package ViewModel;

import Fragment.Constants;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class AssetsForm {

    private JCheckBox enableSaleValueCheckBox;
    private JCheckBox enableRentabilityCheckBox;
    private JTextField assetNameField;
    private JComboBox assetTypeComboBox;
    private JTextField rentabilityPercentageField;
    private JComboBox assetCategoryComboBox;
    private JTextField saleValueField;
    private JPanel assetsPanel;

    public String getAssetName() {
        return assetNameField.getText();
    }

    public byte getAssetType() {
        if (assetTypeComboBox.getSelectedIndex() == 1) {
            return Constants.CURRENT;
        } else if (assetTypeComboBox.getSelectedIndex() == 2) {
            return Constants.NO_CURRENT;

        } else {
            return Constants.NONE;
        }

    }

    public int getRentabilityPercentage() {
        if (rentabilityPercentageField.isEnabled()) {
            return Integer.valueOf(rentabilityPercentageField.getText());
        } else {
            return 0;
        }

    }

    public byte getAssetCategory() {
        if (assetCategoryComboBox.getSelectedIndex() == 0) {
            return Constants.NONE;
        } else {
            return (byte) assetCategoryComboBox.getSelectedIndex();
        }
    }

    public int getSaleValue() {
        if (saleValueField.isEnabled()) {
            return Integer.valueOf(saleValueField.getText());
        } else {
            return 0;
        }
    }

    public AssetsForm() {
        {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
            $$$setupUI$$$();
        }
        assetTypeComboBox.addItem("Seleccione");
        assetTypeComboBox.addItem("Corriente");
        assetTypeComboBox.addItem("No Corriente");
        assetCategoryComboBox.addItem("Seleccione");
        assetCategoryComboBox.addItem("Con Iva");
        assetCategoryComboBox.addItem("Sin Iva");


        enableRentabilityCheckBox.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (enableRentabilityCheckBox.isSelected()) {
                    rentabilityPercentageField.setEnabled(true);
                } else {
                    rentabilityPercentageField.setText("");
                    rentabilityPercentageField.setEnabled(false);
                }
            }
        });
        enableSaleValueCheckBox.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (enableSaleValueCheckBox.isSelected()) {
                    saleValueField.setEnabled(true);
                } else {
                    saleValueField.setText("");
                    saleValueField.setEnabled(false);
                }
            }
        });
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        assetsPanel = new JPanel();
        assetsPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Nombre");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        assetsPanel.add(label1, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        assetsPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        assetsPanel.add(spacer2, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Tipo");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        assetsPanel.add(label2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        assetsPanel.add(spacer3, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("% rentabilidad");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        assetsPanel.add(label3, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        assetsPanel.add(spacer4, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Categoría");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        assetsPanel.add(label4, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        assetsPanel.add(spacer5, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Valor aprox de venta");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        assetsPanel.add(label5, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.VERTICAL;
        assetsPanel.add(spacer6, gbc);
        assetNameField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        assetsPanel.add(assetNameField, gbc);
        assetTypeComboBox = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        assetsPanel.add(assetTypeComboBox, gbc);
        rentabilityPercentageField = new JTextField();
        rentabilityPercentageField.setEnabled(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        assetsPanel.add(rentabilityPercentageField, gbc);
        assetCategoryComboBox = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        assetsPanel.add(assetCategoryComboBox, gbc);
        saleValueField = new JTextField();
        saleValueField.setEnabled(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        assetsPanel.add(saleValueField, gbc);
        enableSaleValueCheckBox = new JCheckBox();
        enableSaleValueCheckBox.setSelected(false);
        enableSaleValueCheckBox.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        assetsPanel.add(enableSaleValueCheckBox, gbc);
        enableRentabilityCheckBox = new JCheckBox();
        enableRentabilityCheckBox.setSelected(false);
        enableRentabilityCheckBox.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        assetsPanel.add(enableRentabilityCheckBox, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return assetsPanel;
    }

}
