package ViewModel;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

public class RegistroFormulario {
    private JComboBox tipoFormularioComboBox;
    private JTextField valorField;
    private JComboBox fuenteComboBox;
    private JComboBox motivoComboBox;
    private JTextField comentariosField;
    private JPanel panelRegAssetPasive;
    private JButton submitButton;
    private JPanel generalForm;
    private JScrollPane registroScrollPane;
    private String[] motivosEgresos = {
            "ninguno",
            "gasto Regular",
            "compra activo",
            "pago pasivo"

    };
    private String[] tipoFormulario = {
            "Seleccione",
            "Ingresos",
            "Egresos"
    };
    private JFrame frame = new JFrame("formulario registro");

    public RegistroFormulario() {
        {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
            $$$setupUI$$$();
        }
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.add($$$getRootComponent$$$());
        frame.setVisible(true);
        tipoFormularioComboBox.addItem(tipoFormulario[0]);
        tipoFormularioComboBox.addItem(tipoFormulario[1]);
        tipoFormularioComboBox.addItem(tipoFormulario[2]);

        motivoComboBox.addItem(motivosEgresos[0]);
        motivoComboBox.addItem(motivosEgresos[1]);
        motivoComboBox.addItem(motivosEgresos[2]);
        motivoComboBox.addItem(motivosEgresos[3]);


        motivoComboBox.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                Component[] y = panelRegAssetPasive.getComponents();
                if (e.getStateChange() == 1 && motivoComboBox.getSelectedIndex() == 2) {
                    AssetsForm p = new AssetsForm();
                    if (y.length == 0) {
                        panelRegAssetPasive.add(p.$$$getRootComponent$$$());
                        panelRegAssetPasive.setVisible(true);
                    } else {
                        panelRegAssetPasive.remove(0);
                        panelRegAssetPasive.add(p.$$$getRootComponent$$$());
                        panelRegAssetPasive.setVisible(true);
                    }

                } else {
                    if (y.length == 1) {
                        panelRegAssetPasive.remove(0);
                        panelRegAssetPasive.setVisible(false);
                    }
                }
            }
        });
        tipoFormularioComboBox.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    int x = tipoFormularioComboBox.getSelectedIndex();
                    if (x == 2) {
                        valorField.setEnabled(true);
                        motivoComboBox.setEnabled(true);
                        fuenteComboBox.setEnabled(true);

                    }
                }
            }
        });
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        registroScrollPane = new JScrollPane();
        registroScrollPane.setPreferredSize(new Dimension(500, 600));
        registroScrollPane.setRequestFocusEnabled(true);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel1.setPreferredSize(new Dimension(500, 600));
        registroScrollPane.setViewportView(panel1);
        generalForm = new JPanel();
        generalForm.setLayout(new GridBagLayout());
        generalForm.setPreferredSize(new Dimension(490, 200));
        panel1.add(generalForm);
        final JLabel label1 = new JLabel();
        label1.setPreferredSize(new Dimension(150, 20));
        label1.setText("tipo de formulario");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        generalForm.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("valor");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        generalForm.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("fuente");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        generalForm.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Motivo");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        generalForm.add(label4, gbc);
        motivoComboBox = new JComboBox();
        motivoComboBox.setEnabled(false);
        motivoComboBox.setPreferredSize(new Dimension(150, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        generalForm.add(motivoComboBox, gbc);
        tipoFormularioComboBox = new JComboBox();
        tipoFormularioComboBox.setPreferredSize(new Dimension(150, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        generalForm.add(tipoFormularioComboBox, gbc);
        valorField = new JTextField();
        valorField.setEnabled(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        generalForm.add(valorField, gbc);
        fuenteComboBox = new JComboBox();
        fuenteComboBox.setEnabled(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        generalForm.add(fuenteComboBox, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        generalForm.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.VERTICAL;
        generalForm.add(spacer2, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        generalForm.add(spacer3, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("comentarios");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        generalForm.add(label5, gbc);
        comentariosField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        generalForm.add(comentariosField, gbc);
        panelRegAssetPasive = new JPanel();
        panelRegAssetPasive.setLayout(new GridBagLayout());
        panelRegAssetPasive.setEnabled(true);
        panelRegAssetPasive.setPreferredSize(new Dimension(490, 270));
        panelRegAssetPasive.setVisible(false);
        panel1.add(panelRegAssetPasive);
        submitButton = new JButton();
        submitButton.setHorizontalAlignment(0);
        submitButton.setLabel("confirmar");
        submitButton.setText("confirmar");
        panel1.add(submitButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return registroScrollPane;
    }

}
