package View.MainApp;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class LateralBar {
    private JPanel principal;
    private JScrollPane FinSpaceScrollPane;
    private JLabel homeLabel;
    private JLabel cashFlowLabel;
    private JLabel AssetsLabel;
    private JLabel pasivesLabel;
    private JLabel StatsLabel;
    private JLabel InventoryLabel;

    public LateralBar() {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
        principal.setVisible(true);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        principal = new JPanel();
        principal.setLayout(new GridBagLayout());
        principal.setBackground(new Color(-1));
        principal.setMaximumSize(new Dimension(200, 700));
        principal.setMinimumSize(new Dimension(200, 700));
        principal.setOpaque(false);
        principal.setPreferredSize(new Dimension(200, 700));
        homeLabel = new JLabel();
        homeLabel.setForeground(new Color(-16777216));
        homeLabel.setText("Home");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        principal.add(homeLabel, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.VERTICAL;
        principal.add(spacer1, gbc);
        cashFlowLabel = new JLabel();
        cashFlowLabel.setForeground(new Color(-16777216));
        cashFlowLabel.setText("Flujo de caja");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        principal.add(cashFlowLabel, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.VERTICAL;
        principal.add(spacer2, gbc);
        AssetsLabel = new JLabel();
        AssetsLabel.setForeground(new Color(-16777216));
        AssetsLabel.setText("Activos");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        principal.add(AssetsLabel, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.VERTICAL;
        principal.add(spacer3, gbc);
        pasivesLabel = new JLabel();
        pasivesLabel.setForeground(new Color(-16777216));
        pasivesLabel.setText("Pasivos");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        principal.add(pasivesLabel, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 9;
        gbc.fill = GridBagConstraints.VERTICAL;
        principal.add(spacer4, gbc);
        StatsLabel = new JLabel();
        StatsLabel.setForeground(new Color(-16777216));
        StatsLabel.setText("Estadísticas");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 10;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        principal.add(StatsLabel, gbc);
        final JPanel spacer5 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 11;
        gbc.fill = GridBagConstraints.VERTICAL;
        principal.add(spacer5, gbc);
        InventoryLabel = new JLabel();
        InventoryLabel.setForeground(new Color(-16777216));
        InventoryLabel.setText("Inventario");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 12;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        principal.add(InventoryLabel, gbc);
        final JPanel spacer6 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 13;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.ipady = 25;
        principal.add(spacer6, gbc);
        final JSeparator separator1 = new JSeparator();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 14;
        gbc.fill = GridBagConstraints.BOTH;
        principal.add(separator1, gbc);
        FinSpaceScrollPane = new JScrollPane();
        FinSpaceScrollPane.setMaximumSize(new Dimension(250, 350));
        FinSpaceScrollPane.setMinimumSize(new Dimension(250, 350));
        FinSpaceScrollPane.setOpaque(false);
        FinSpaceScrollPane.setPreferredSize(new Dimension(250, 350));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 16;
        gbc.fill = GridBagConstraints.BOTH;
        principal.add(FinSpaceScrollPane, gbc);
        final JPanel spacer7 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.ipady = 10;
        principal.add(spacer7, gbc);
        final JPanel spacer8 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 15;
        gbc.fill = GridBagConstraints.VERTICAL;
        gbc.ipady = 25;
        principal.add(spacer8, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.setMaximumSize(new Dimension(50, 50));
        panel1.setMinimumSize(new Dimension(50, 50));
        panel1.setPreferredSize(new Dimension(50, 50));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        principal.add(panel1, gbc);
        final JPanel spacer9 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        principal.add(spacer9, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return principal;
    }

}
