package View.MainApp.MainPanels;

import javax.swing.*;
import java.awt.*;

public class HomePanel {
    private JPanel principal;
    private JButton nuevoRegistroButton;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        principal = new JPanel();
        principal.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        nuevoRegistroButton = new JButton();
        nuevoRegistroButton.setText("nuevo registro");
        principal.add(nuevoRegistroButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return principal;
    }

}
